version: "{build}"

build_script:
  - mv "../${APPVEYOR_PROJECT_SLUG}" "../${APPVEYOR_PROJECT_NAME}"
  - make ci
  - mv "../${APPVEYOR_PROJECT_NAME}" "../${APPVEYOR_PROJECT_SLUG}"

#artifacts:
#  - path: 'ponyc-*.zip'

#deploy:
  # On branche `release`, deploy (and publish) artifacts
  # to the ponyc-win projects on Bintray.
#  - provider: BinTray
#    username: pony-buildbot-2
#    api_key:
#        secure: 4KgdDQLp2kX816XH27d5xdJBPlKGhYXN6ttdHTSt5qe1MVIF+/VResUstg0zuJ6m
#    subject: pony-language
#    repo: ponyc-win
#    package: ponyc
#    on:
#        branch: release
#        llvm: 7.0.1
#        configuration: release
#    publish: true
