all:
	/Volumes/Development/Development/pony/ponyc/build/release/ponyc -o ./build/
	./build/error_value_1

debug:
	/Volumes/Development/Development/pony/ponyc/build/debug/ponyc -d -o ./build/
	lldb ./build/error_value_1